### PR TITLE
Do not remove empty lines in fragments 

### PR DESCRIPTION
**Pull request by sapegin**
1. Fix tests in master.
2. Replace a custom `unindent` function that strips empty lines with the unindent package.

### CODE REVIEW

**Comment by aslakhellesoy** [comment]
Thanks for this. We're not using GitBook anymore, so feel free to fork this and maintain the code if you want.

**Comment by sapegin** [comment]
@aslakhellesoy Another option is to give us rights to the repo and npm package. What would be better for you?

**Comment by aslakhellesoy** [comment]
Yep that works! Who should I give npm karma to?

**Comment by aslakhellesoy** [comment]
I need your npm email

**Comment by aslakhellesoy** [comment]
Ping @sapegin

**Comment by sapegin** [comment]
@aslakhellesoy Sorry for the delay, could you please send an invite to my colleague — @freethan?

**Comment by aslakhellesoy** [comment]
@sapegin npm permissions are granted by email, not username

**Comment by sapegin** [comment]
Repo: @freethan
npm: georghios.skettos@here.com

**Comment by aslakhellesoy** [comment]
@sapegin let me know when georghios has created an npm account. I can't give him npm access before he has.

**Comment by freethan** [comment]
Hi @aslakhellesoy and thank you for doing this. I will have to come back to you after New Year's, we need to sort out some internal issues first.

Apologies for  the false start.

**Comment by freethan** [comment]
Hi @aslakhellesoy and a belated happy new year.

please let us know how comfortable you would be with:

* Adding a copyright notice and a permissive license such as BSD-2-Clause, BSD-3-Clause or MIT to the repo.
* Updating the README file to "deprecate" / state something like "please use the heremaps repo" as it would become the successor of your project in terms of development.

That would allow us to fork the repo and produce NPM packages without assuming ownership and producing conflicts with existing people referencing this plugin. Our plugin would then be available under heremaps/gitbook-plugin-{still-to-be-determined}

**Comment by aslakhellesoy** [comment]
The lack of a `LICENSE` file was an oversight. I've just added one.

**Pull request closed without merging**
